// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import org.rooinaction.coursemanager.model.Address;

privileged aspect Address_Roo_JavaBean {
    
    public String Address.getAddressLine1() {
        return this.addressLine1;
    }
    
    public void Address.setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    
    public String Address.getAddressLine2() {
        return this.addressLine2;
    }
    
    public void Address.setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    
    public String Address.getCity() {
        return this.city;
    }
    
    public void Address.setCity(String city) {
        this.city = city;
    }
    
    public String Address.getStateCode() {
        return this.stateCode;
    }
    
    public void Address.setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    
    public String Address.getPostalCode() {
        return this.postalCode;
    }
    
    public void Address.setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
}
