// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import org.rooinaction.coursemanager.model.Student;

privileged aspect Student_Roo_JavaBean {
    
    public String Student.getEmergencyContactName() {
        return this.emergencyContactName;
    }
    
    public void Student.setEmergencyContactName(String emergencyContactName) {
        this.emergencyContactName = emergencyContactName;
    }
    
    public String Student.getEmergencyContactInfo() {
        return this.emergencyContactInfo;
    }
    
    public void Student.setEmergencyContactInfo(String emergencyContactInfo) {
        this.emergencyContactInfo = emergencyContactInfo;
    }
    
    public String Student.getDietaryRestrictions() {
        return this.dietaryRestrictions;
    }
    
    public void Student.setDietaryRestrictions(String dietaryRestrictions) {
        this.dietaryRestrictions = dietaryRestrictions;
    }
    
}
