// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.jsf.converter;

import org.rooinaction.coursemanager.jsf.converter.RegistrationConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RegistrationConverter_Roo_Configurable {
    
    declare @type: RegistrationConverter: @Configurable;
    
}
