// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.jsf.converter;

import org.rooinaction.coursemanager.jsf.converter.StudentConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StudentConverter_Roo_Configurable {
    
    declare @type: StudentConverter: @Configurable;
    
}
