// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.rooinaction.coursemanager.domain.Instructor;
import org.rooinaction.coursemanager.domain.InstructorDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect InstructorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InstructorDataOnDemand: @Component;
    
    private Random InstructorDataOnDemand.rnd = new SecureRandom();
    
    private List<Instructor> InstructorDataOnDemand.data;
    
    public Instructor InstructorDataOnDemand.getNewTransientInstructor(int index) {
        Instructor obj = new Instructor();
        setName(obj, index);
        return obj;
    }
    
    public void InstructorDataOnDemand.setName(Instructor obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Instructor InstructorDataOnDemand.getSpecificInstructor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Instructor obj = data.get(index);
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public Instructor InstructorDataOnDemand.getRandomInstructor() {
        init();
        Instructor obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Instructor.findInstructor(id);
    }
    
    public boolean InstructorDataOnDemand.modifyInstructor(Instructor obj) {
        return false;
    }
    
    public void InstructorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Instructor.findInstructorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Instructor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Instructor>();
        for (int i = 0; i < 10; i++) {
            Instructor obj = getNewTransientInstructor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
