// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.domain;

import org.rooinaction.coursemanager.domain.CourseDetail;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CourseDetail_Roo_Configurable {
    
    declare @type: CourseDetail: @Configurable;
    
}
