// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.rooinaction.coursemanager.client.managed.request.ApplicationRequestFactory;
import org.rooinaction.coursemanager.client.managed.ui.CourseDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.CourseEditView;
import org.rooinaction.coursemanager.client.managed.ui.CourseListView;
import org.rooinaction.coursemanager.client.managed.ui.CourseMobileDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.CourseMobileEditView;
import org.rooinaction.coursemanager.client.scaffold.ScaffoldApp;
import org.rooinaction.coursemanager.client.scaffold.place.CreateAndEditProxy;
import org.rooinaction.coursemanager.client.scaffold.place.FindAndEditProxy;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyPlace;
import org.rooinaction.coursemanager.proxy.CourseProxy;
import org.rooinaction.coursemanager.request.CourseRequest;
import org.rooinaction.coursemanager.shared.CourseTypeEnum;

public abstract class CourseActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        CourseEditView.instance().setCreating(true);
        final CourseRequest request = requests.courseRequest();
        Activity activity = new CreateAndEditProxy<CourseProxy>(CourseProxy.class, request, ScaffoldApp.isMobile() ? CourseMobileEditView.instance() : CourseEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(CourseProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new CourseEditActivityWrapper(requests, ScaffoldApp.isMobile() ? CourseMobileEditView.instance() : CourseEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<org.rooinaction.coursemanager.proxy.CourseProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<CourseProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        CourseEditView.instance().setCreating(false);
        EntityProxyId<CourseProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<CourseProxy>(proxyId, requests, ScaffoldApp.isMobile() ? CourseMobileEditView.instance() : CourseEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(CourseProxy proxy) {
                CourseRequest request = requests.courseRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new CourseEditActivityWrapper(requests, ScaffoldApp.isMobile() ? CourseMobileEditView.instance() : CourseEditView.instance(), activity, proxyId);
    }
}
