// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.rooinaction.coursemanager.client.managed.request.ApplicationRequestFactory;
import org.rooinaction.coursemanager.client.managed.ui.desktop.InstructorDesktopDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.desktop.InstructorDesktopEditView;
import org.rooinaction.coursemanager.client.managed.ui.desktop.InstructorDesktopListView;
import org.rooinaction.coursemanager.client.managed.ui.mobile.InstructorMobileDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.mobile.InstructorMobileEditView;
import org.rooinaction.coursemanager.client.scaffold.ScaffoldApp;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyPlace;
import org.rooinaction.coursemanager.web.proxy.InstructorProxy;
import org.rooinaction.coursemanager.web.request.InstructorRequest;

public abstract class InstructorActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        InstructorDesktopEditView.instance().setCreating(true);
        Activity activity = new InstructorEditActivity(null, factory, ScaffoldApp.isMobile() ? InstructorMobileEditView.instance() : InstructorDesktopEditView.instance(), placeController);
        return new InstructorEditActivityWrapper(factory, ScaffoldApp.isMobile() ? InstructorMobileEditView.instance() : InstructorDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<InstructorProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<InstructorProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        InstructorDesktopEditView.instance().setCreating(false);
        EntityProxyId<InstructorProxy> proxyId = coerceId(place);
        Activity activity = new InstructorEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? InstructorMobileEditView.instance() : InstructorDesktopEditView.instance(), placeController);
        return new InstructorEditActivityWrapper(factory, ScaffoldApp.isMobile() ? InstructorMobileEditView.instance() : InstructorDesktopEditView.instance(), activity, proxyId);
    }
}
