// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.activity;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.rooinaction.coursemanager.client.managed.request.ApplicationRequestFactory;
import org.rooinaction.coursemanager.client.managed.ui.desktop.RegistrationDesktopDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.desktop.RegistrationDesktopEditView;
import org.rooinaction.coursemanager.client.managed.ui.desktop.RegistrationDesktopListView;
import org.rooinaction.coursemanager.client.managed.ui.mobile.RegistrationMobileDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.mobile.RegistrationMobileEditView;
import org.rooinaction.coursemanager.client.scaffold.ScaffoldApp;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyPlace;
import org.rooinaction.coursemanager.web.proxy.RegistrationProxy;
import org.rooinaction.coursemanager.web.request.RegistrationRequest;

public abstract class RegistrationActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory factory;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RegistrationDesktopEditView.instance().setCreating(true);
        Activity activity = new RegistrationEditActivity(null, factory, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationDesktopEditView.instance(), placeController);
        return new RegistrationEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationDesktopEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<RegistrationProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RegistrationProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RegistrationDesktopEditView.instance().setCreating(false);
        EntityProxyId<RegistrationProxy> proxyId = coerceId(place);
        Activity activity = new RegistrationEditActivity(proxyId, factory, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationDesktopEditView.instance(), placeController);
        return new RegistrationEditActivityWrapper(factory, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationDesktopEditView.instance(), activity, proxyId);
    }
}
