// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rooinaction.cmsapp.domain;

import com.rooinaction.cmsapp.domain.CourseDetailsDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CourseDetailsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CourseDetailsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CourseDetailsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CourseDetailsIntegrationTest: @Transactional;
    
    @Autowired
    private CourseDetailsDataOnDemand CourseDetailsIntegrationTest.dod;
    
    @Test
    public void CourseDetailsIntegrationTest.testCountCourseDetailses() {
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", dod.getRandomCourseDetails());
        long count = CourseDetails.countCourseDetailses();
        Assert.assertTrue("Counter for 'CourseDetails' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testFindCourseDetails() {
        CourseDetails obj = dod.getRandomCourseDetails();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to provide an identifier", id);
        obj = CourseDetails.findCourseDetails(id);
        Assert.assertNotNull("Find method for 'CourseDetails' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CourseDetails' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testFindAllCourseDetailses() {
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", dod.getRandomCourseDetails());
        long count = CourseDetails.countCourseDetailses();
        Assert.assertTrue("Too expensive to perform a find all test for 'CourseDetails', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CourseDetails> result = CourseDetails.findAllCourseDetailses();
        Assert.assertNotNull("Find all method for 'CourseDetails' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CourseDetails' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testFindCourseDetailsEntries() {
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", dod.getRandomCourseDetails());
        long count = CourseDetails.countCourseDetailses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CourseDetails> result = CourseDetails.findCourseDetailsEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CourseDetails' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CourseDetails' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testFlush() {
        CourseDetails obj = dod.getRandomCourseDetails();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to provide an identifier", id);
        obj = CourseDetails.findCourseDetails(id);
        Assert.assertNotNull("Find method for 'CourseDetails' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCourseDetails(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CourseDetails' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testMergeUpdate() {
        CourseDetails obj = dod.getRandomCourseDetails();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to provide an identifier", id);
        obj = CourseDetails.findCourseDetails(id);
        boolean modified =  dod.modifyCourseDetails(obj);
        Integer currentVersion = obj.getVersion();
        CourseDetails merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CourseDetails' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", dod.getRandomCourseDetails());
        CourseDetails obj = dod.getNewTransientCourseDetails(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CourseDetails' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CourseDetails' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CourseDetailsIntegrationTest.testRemove() {
        CourseDetails obj = dod.getRandomCourseDetails();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CourseDetails' failed to provide an identifier", id);
        obj = CourseDetails.findCourseDetails(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CourseDetails' with identifier '" + id + "'", CourseDetails.findCourseDetails(id));
    }
    
}
