// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.request;

import org.rooinaction.coursemanager.shared.scaffold.ScaffoldRequestFactory;
import org.rooinaction.coursemanager.web.gwt.requests.CourseRequest;
import org.rooinaction.coursemanager.web.gwt.requests.InstructorRequest;
import org.rooinaction.coursemanager.web.gwt.requests.OfferingRequest;
import org.rooinaction.coursemanager.web.gwt.requests.RegistrationRequest;
import org.rooinaction.coursemanager.web.gwt.requests.StudentRequest;
import org.rooinaction.coursemanager.web.gwt.requests.TagRequest;
import org.rooinaction.coursemanager.web.gwt.requests.TrainingProgramRequest;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory {

    CourseRequest courseRequest();

    InstructorRequest instructorRequest();

    OfferingRequest offeringRequest();

    RegistrationRequest registrationRequest();

    StudentRequest studentRequest();

    TagRequest tagRequest();

    TrainingProgramRequest trainingProgramRequest();
}
