// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import org.rooinaction.coursemanager.client.managed.request.ApplicationEntityTypesProcessor;
import org.rooinaction.coursemanager.client.managed.request.ApplicationRequestFactory;
import org.rooinaction.coursemanager.client.managed.ui.CourseListView;
import org.rooinaction.coursemanager.client.managed.ui.CourseMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.InstructorListView;
import org.rooinaction.coursemanager.client.managed.ui.InstructorMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.OfferingListView;
import org.rooinaction.coursemanager.client.managed.ui.OfferingMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationListView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.StudentListView;
import org.rooinaction.coursemanager.client.managed.ui.StudentMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.TagListView;
import org.rooinaction.coursemanager.client.managed.ui.TagMobileListView;
import org.rooinaction.coursemanager.client.managed.ui.TrainingProgramListView;
import org.rooinaction.coursemanager.client.managed.ui.TrainingProgramMobileListView;
import org.rooinaction.coursemanager.client.scaffold.ScaffoldApp;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyListPlace;
import org.rooinaction.coursemanager.web.gwt.proxies.CourseProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.InstructorProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.RegistrationProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.StudentProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TagProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TrainingProgramProxy;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleCourse(CourseProxy isNull) {
                setResult(new CourseListActivity(requests, ScaffoldApp.isMobile() ? CourseMobileListView.instance() : CourseListView.instance(), placeController));
            }

            @Override
            public void handleInstructor(InstructorProxy isNull) {
                setResult(new InstructorListActivity(requests, ScaffoldApp.isMobile() ? InstructorMobileListView.instance() : InstructorListView.instance(), placeController));
            }

            @Override
            public void handleOffering(OfferingProxy isNull) {
                setResult(new OfferingListActivity(requests, ScaffoldApp.isMobile() ? OfferingMobileListView.instance() : OfferingListView.instance(), placeController));
            }

            @Override
            public void handleRegistration(RegistrationProxy isNull) {
                setResult(new RegistrationListActivity(requests, ScaffoldApp.isMobile() ? RegistrationMobileListView.instance() : RegistrationListView.instance(), placeController));
            }

            @Override
            public void handleStudent(StudentProxy isNull) {
                setResult(new StudentListActivity(requests, ScaffoldApp.isMobile() ? StudentMobileListView.instance() : StudentListView.instance(), placeController));
            }

            @Override
            public void handleTag(TagProxy isNull) {
                setResult(new TagListActivity(requests, ScaffoldApp.isMobile() ? TagMobileListView.instance() : TagListView.instance(), placeController));
            }

            @Override
            public void handleTrainingProgram(TrainingProgramProxy isNull) {
                setResult(new TrainingProgramListActivity(requests, ScaffoldApp.isMobile() ? TrainingProgramMobileListView.instance() : TrainingProgramListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
