// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceController;
import com.google.web.bindery.requestfactory.shared.EntityProxyId;
import com.google.web.bindery.requestfactory.shared.RequestContext;
import org.rooinaction.coursemanager.client.managed.request.ApplicationRequestFactory;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationEditView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationListView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationMobileDetailsView;
import org.rooinaction.coursemanager.client.managed.ui.RegistrationMobileEditView;
import org.rooinaction.coursemanager.client.scaffold.ScaffoldApp;
import org.rooinaction.coursemanager.client.scaffold.place.CreateAndEditProxy;
import org.rooinaction.coursemanager.client.scaffold.place.FindAndEditProxy;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyPlace;
import org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.RegistrationProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.StudentProxy;
import org.rooinaction.coursemanager.web.gwt.requests.RegistrationRequest;

public abstract class RegistrationActivitiesMapper_Roo_Gwt {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    protected Activity makeCreateActivity() {
        RegistrationEditView.instance().setCreating(true);
        final RegistrationRequest request = requests.registrationRequest();
        Activity activity = new CreateAndEditProxy<RegistrationProxy>(RegistrationProxy.class, request, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(RegistrationProxy proxy) {
                request.persist().using(proxy);
                return request;
            }
        };
        return new RegistrationEditActivityWrapper(requests, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationEditView.instance(), activity, null);
    }

    @SuppressWarnings("unchecked")
    protected EntityProxyId<org.rooinaction.coursemanager.web.gwt.proxies.RegistrationProxy> coerceId(ProxyPlace place) {
        return (EntityProxyId<RegistrationProxy>) place.getProxyId();
    }

    protected Activity makeEditActivity(ProxyPlace place) {
        RegistrationEditView.instance().setCreating(false);
        EntityProxyId<RegistrationProxy> proxyId = coerceId(place);
        Activity activity = new FindAndEditProxy<RegistrationProxy>(proxyId, requests, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationEditView.instance(), placeController) {

            @Override
            protected RequestContext createSaveRequest(RegistrationProxy proxy) {
                RegistrationRequest request = requests.registrationRequest();
                request.persist().using(proxy);
                return request;
            }
        };
        return new RegistrationEditActivityWrapper(requests, ScaffoldApp.isMobile() ? RegistrationMobileEditView.instance() : RegistrationEditView.instance(), activity, proxyId);
    }
}
