// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.io.Serializable;

privileged aspect TrainingProgram_Roo_Serializable {
    
    declare parents: TrainingProgram implements Serializable;
    
    private static final long TrainingProgram.serialVersionUID = 1L;
    
}
