// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rooinaction.cmsapp.domain;

import com.rooinaction.cmsapp.domain.CourseDetails;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect CourseDetailsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CourseDetailsDataOnDemand: @Component;
    
    private Random CourseDetailsDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<CourseDetails> CourseDetailsDataOnDemand.data;
    
    public CourseDetails CourseDetailsDataOnDemand.getNewTransientCourseDetails(int index) {
        com.rooinaction.cmsapp.domain.CourseDetails obj = new com.rooinaction.cmsapp.domain.CourseDetails();
        obj.setName("name_" + index);
        return obj;
    }
    
    public CourseDetails CourseDetailsDataOnDemand.getSpecificCourseDetails(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        CourseDetails obj = data.get(index);
        return CourseDetails.findCourseDetails(obj.getId());
    }
    
    public CourseDetails CourseDetailsDataOnDemand.getRandomCourseDetails() {
        init();
        CourseDetails obj = data.get(rnd.nextInt(data.size()));
        return CourseDetails.findCourseDetails(obj.getId());
    }
    
    public boolean CourseDetailsDataOnDemand.modifyCourseDetails(CourseDetails obj) {
        return false;
    }
    
    public void CourseDetailsDataOnDemand.init() {
        data = com.rooinaction.cmsapp.domain.CourseDetails.findCourseDetailsEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'CourseDetails' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.rooinaction.cmsapp.domain.CourseDetails>();
        for (int i = 0; i < 10; i++) {
            com.rooinaction.cmsapp.domain.CourseDetails obj = getNewTransientCourseDetails(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
