// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rooinaction.cmsapp.domain;

import com.rooinaction.cmsapp.domain.CourseCatalogDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CourseCatalogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CourseCatalogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CourseCatalogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CourseCatalogIntegrationTest: @Transactional;
    
    @Autowired
    private CourseCatalogDataOnDemand CourseCatalogIntegrationTest.dod;
    
    @Test
    public void CourseCatalogIntegrationTest.testCountCourseCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", dod.getRandomCourseCatalog());
        long count = com.rooinaction.cmsapp.domain.CourseCatalog.countCourseCatalogs();
        org.junit.Assert.assertTrue("Counter for 'CourseCatalog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testFindCourseCatalog() {
        com.rooinaction.cmsapp.domain.CourseCatalog obj = dod.getRandomCourseCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to provide an identifier", id);
        obj = com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'CourseCatalog' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CourseCatalog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testFindAllCourseCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", dod.getRandomCourseCatalog());
        long count = com.rooinaction.cmsapp.domain.CourseCatalog.countCourseCatalogs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CourseCatalog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.rooinaction.cmsapp.domain.CourseCatalog> result = com.rooinaction.cmsapp.domain.CourseCatalog.findAllCourseCatalogs();
        org.junit.Assert.assertNotNull("Find all method for 'CourseCatalog' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CourseCatalog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testFindCourseCatalogEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", dod.getRandomCourseCatalog());
        long count = com.rooinaction.cmsapp.domain.CourseCatalog.countCourseCatalogs();
        if (count > 20) count = 20;
        java.util.List<com.rooinaction.cmsapp.domain.CourseCatalog> result = com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalogEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CourseCatalog' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CourseCatalog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testFlush() {
        com.rooinaction.cmsapp.domain.CourseCatalog obj = dod.getRandomCourseCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to provide an identifier", id);
        obj = com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'CourseCatalog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCourseCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CourseCatalog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testMerge() {
        com.rooinaction.cmsapp.domain.CourseCatalog obj = dod.getRandomCourseCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to provide an identifier", id);
        obj = com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalog(id);
        boolean modified =  dod.modifyCourseCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.rooinaction.cmsapp.domain.CourseCatalog merged = (com.rooinaction.cmsapp.domain.CourseCatalog) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CourseCatalog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", dod.getRandomCourseCatalog());
        com.rooinaction.cmsapp.domain.CourseCatalog obj = dod.getNewTransientCourseCatalog(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CourseCatalog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CourseCatalog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CourseCatalogIntegrationTest.testRemove() {
        com.rooinaction.cmsapp.domain.CourseCatalog obj = dod.getRandomCourseCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CourseCatalog' failed to provide an identifier", id);
        obj = com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalog(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CourseCatalog' with identifier '" + id + "'", com.rooinaction.cmsapp.domain.CourseCatalog.findCourseCatalog(id));
    }
    
}
