// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rooinaction.cmsapp.domain;

import com.rooinaction.cmsapp.domain.Student;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect StudentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudentDataOnDemand: @Component;
    
    private Random StudentDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Student> StudentDataOnDemand.data;
    
    public Student StudentDataOnDemand.getNewTransientStudent(int index) {
        com.rooinaction.cmsapp.domain.Student obj = new com.rooinaction.cmsapp.domain.Student();
        obj.setName("name_" + index);
        obj.setAge(new Integer(index));
        obj.setId(new Integer(index).longValue());
        return obj;
    }
    
    public Student StudentDataOnDemand.getSpecificStudent(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Student obj = data.get(index);
        return Student.findStudent(obj.get_id());
    }
    
    public Student StudentDataOnDemand.getRandomStudent() {
        init();
        Student obj = data.get(rnd.nextInt(data.size()));
        return Student.findStudent(obj.get_id());
    }
    
    public boolean StudentDataOnDemand.modifyStudent(Student obj) {
        return false;
    }
    
    public void StudentDataOnDemand.init() {
        data = com.rooinaction.cmsapp.domain.Student.findStudentEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Student' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.rooinaction.cmsapp.domain.Student>();
        for (int i = 0; i < 10; i++) {
            com.rooinaction.cmsapp.domain.Student obj = getNewTransientStudent(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
