// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooina.coursemanager.model;

import java.util.List;
import java.util.Random;
import org.rooina.coursemanager.model.TrainingProgram;
import org.springframework.stereotype.Component;

privileged aspect TrainingProgramDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TrainingProgramDataOnDemand: @Component;
    
    private Random TrainingProgramDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<TrainingProgram> TrainingProgramDataOnDemand.data;
    
    public TrainingProgram TrainingProgramDataOnDemand.getNewTransientTrainingProgram(int index) {
        org.rooina.coursemanager.model.TrainingProgram obj = new org.rooina.coursemanager.model.TrainingProgram();
        setName(obj, index);
        return obj;
    }
    
    public void TrainingProgramDataOnDemand.setName(TrainingProgram obj, int index) {
        java.lang.String name = "name_" + index;
        obj.setName(name);
    }
    
    public TrainingProgram TrainingProgramDataOnDemand.getSpecificTrainingProgram(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TrainingProgram obj = data.get(index);
        return TrainingProgram.findTrainingProgram(obj.getId());
    }
    
    public TrainingProgram TrainingProgramDataOnDemand.getRandomTrainingProgram() {
        init();
        TrainingProgram obj = data.get(rnd.nextInt(data.size()));
        return TrainingProgram.findTrainingProgram(obj.getId());
    }
    
    public boolean TrainingProgramDataOnDemand.modifyTrainingProgram(TrainingProgram obj) {
        return false;
    }
    
    public void TrainingProgramDataOnDemand.init() {
        data = org.rooina.coursemanager.model.TrainingProgram.findTrainingProgramEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'TrainingProgram' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.rooina.coursemanager.model.TrainingProgram>();
        for (int i = 0; i < 10; i++) {
            org.rooina.coursemanager.model.TrainingProgram obj = getNewTransientTrainingProgram(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
