// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.votesecure.domain;

import com.springsource.votesecure.domain.Choice;
import com.springsource.votesecure.domain.ChoiceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ChoiceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ChoiceDataOnDemand: @Component;
    
    private Random ChoiceDataOnDemand.rnd = new SecureRandom();
    
    private List<Choice> ChoiceDataOnDemand.data;
    
    public Choice ChoiceDataOnDemand.getNewTransientChoice(int index) {
        Choice obj = new Choice();
        setDescription(obj, index);
        setNamingChoice(obj, index);
        return obj;
    }
    
    public void ChoiceDataOnDemand.setDescription(Choice obj, int index) {
        String description = "description_" + index;
        if (description.length() > 80) {
            description = description.substring(0, 80);
        }
        obj.setDescription(description);
    }
    
    public void ChoiceDataOnDemand.setNamingChoice(Choice obj, int index) {
        String namingChoice = "namingChoice_" + index;
        if (namingChoice.length() > 30) {
            namingChoice = namingChoice.substring(0, 30);
        }
        obj.setNamingChoice(namingChoice);
    }
    
    public Choice ChoiceDataOnDemand.getSpecificChoice(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Choice obj = data.get(index);
        Long id = obj.getId();
        return Choice.findChoice(id);
    }
    
    public Choice ChoiceDataOnDemand.getRandomChoice() {
        init();
        Choice obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Choice.findChoice(id);
    }
    
    public boolean ChoiceDataOnDemand.modifyChoice(Choice obj) {
        return false;
    }
    
    public void ChoiceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Choice.findChoiceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Choice' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Choice>();
        for (int i = 0; i < 10; i++) {
            Choice obj = getNewTransientChoice(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
