// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.votesecure.domain;

import com.springsource.votesecure.domain.Choice;
import com.springsource.votesecure.domain.ChoiceDataOnDemand;
import com.springsource.votesecure.domain.ChoiceIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ChoiceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ChoiceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ChoiceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ChoiceIntegrationTest: @Transactional;
    
    @Autowired
    ChoiceDataOnDemand ChoiceIntegrationTest.dod;
    
    @Test
    public void ChoiceIntegrationTest.testCountChoices() {
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", dod.getRandomChoice());
        long count = Choice.countChoices();
        Assert.assertTrue("Counter for 'Choice' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ChoiceIntegrationTest.testFindChoice() {
        Choice obj = dod.getRandomChoice();
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Choice' failed to provide an identifier", id);
        obj = Choice.findChoice(id);
        Assert.assertNotNull("Find method for 'Choice' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Choice' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ChoiceIntegrationTest.testFindAllChoices() {
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", dod.getRandomChoice());
        long count = Choice.countChoices();
        Assert.assertTrue("Too expensive to perform a find all test for 'Choice', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Choice> result = Choice.findAllChoices();
        Assert.assertNotNull("Find all method for 'Choice' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Choice' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ChoiceIntegrationTest.testFindChoiceEntries() {
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", dod.getRandomChoice());
        long count = Choice.countChoices();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Choice> result = Choice.findChoiceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Choice' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Choice' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ChoiceIntegrationTest.testFlush() {
        Choice obj = dod.getRandomChoice();
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Choice' failed to provide an identifier", id);
        obj = Choice.findChoice(id);
        Assert.assertNotNull("Find method for 'Choice' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyChoice(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Choice' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChoiceIntegrationTest.testMergeUpdate() {
        Choice obj = dod.getRandomChoice();
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Choice' failed to provide an identifier", id);
        obj = Choice.findChoice(id);
        boolean modified =  dod.modifyChoice(obj);
        Integer currentVersion = obj.getVersion();
        Choice merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Choice' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ChoiceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", dod.getRandomChoice());
        Choice obj = dod.getNewTransientChoice(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Choice' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Choice' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Choice' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ChoiceIntegrationTest.testRemove() {
        Choice obj = dod.getRandomChoice();
        Assert.assertNotNull("Data on demand for 'Choice' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Choice' failed to provide an identifier", id);
        obj = Choice.findChoice(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Choice' with identifier '" + id + "'", Choice.findChoice(id));
    }
    
}
