// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.pizzashop.domain;

import com.springsource.pizzashop.domain.BaseDataOnDemand;
import com.springsource.pizzashop.domain.BaseIntegrationTest;
import com.springsource.pizzashop.repository.BaseRepository;
import com.springsource.pizzashop.service.BaseService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BaseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BaseIntegrationTest: @Transactional;
    
    @Autowired
    BaseDataOnDemand BaseIntegrationTest.dod;
    
    @Autowired
    BaseService BaseIntegrationTest.baseService;
    
    @Autowired
    BaseRepository BaseIntegrationTest.baseRepository;
    
    @Test
    public void BaseIntegrationTest.testCountAllBases() {
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", dod.getRandomBase());
        long count = baseService.countAllBases();
        Assert.assertTrue("Counter for 'Base' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BaseIntegrationTest.testFindBase() {
        Base obj = dod.getRandomBase();
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Base' failed to provide an identifier", id);
        obj = baseService.findBase(id);
        Assert.assertNotNull("Find method for 'Base' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Base' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BaseIntegrationTest.testFindAllBases() {
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", dod.getRandomBase());
        long count = baseService.countAllBases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Base', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Base> result = baseService.findAllBases();
        Assert.assertNotNull("Find all method for 'Base' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Base' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BaseIntegrationTest.testFindBaseEntries() {
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", dod.getRandomBase());
        long count = baseService.countAllBases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Base> result = baseService.findBaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Base' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Base' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BaseIntegrationTest.testFlush() {
        Base obj = dod.getRandomBase();
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Base' failed to provide an identifier", id);
        obj = baseService.findBase(id);
        Assert.assertNotNull("Find method for 'Base' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBase(obj);
        Integer currentVersion = obj.getVersion();
        baseRepository.flush();
        Assert.assertTrue("Version for 'Base' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BaseIntegrationTest.testUpdateBaseUpdate() {
        Base obj = dod.getRandomBase();
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Base' failed to provide an identifier", id);
        obj = baseService.findBase(id);
        boolean modified =  dod.modifyBase(obj);
        Integer currentVersion = obj.getVersion();
        Base merged = baseService.updateBase(obj);
        baseRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Base' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BaseIntegrationTest.testSaveBase() {
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", dod.getRandomBase());
        Base obj = dod.getNewTransientBase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Base' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Base' identifier to be null", obj.getId());
        try {
            baseService.saveBase(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        baseRepository.flush();
        Assert.assertNotNull("Expected 'Base' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BaseIntegrationTest.testDeleteBase() {
        Base obj = dod.getRandomBase();
        Assert.assertNotNull("Data on demand for 'Base' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Base' failed to provide an identifier", id);
        obj = baseService.findBase(id);
        baseService.deleteBase(obj);
        baseRepository.flush();
        Assert.assertNull("Failed to remove 'Base' with identifier '" + id + "'", baseService.findBase(id));
    }
    
}
