// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooina.coursemanager.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.rooina.coursemanager.model.Offering;
import org.rooina.coursemanager.model.OfferingDataOnDemand;
import org.rooina.coursemanager.model.Registration;
import org.rooina.coursemanager.model.Student;
import org.rooina.coursemanager.model.StudentDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RegistrationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RegistrationDataOnDemand: @Component;
    
    private Random RegistrationDataOnDemand.rnd = new SecureRandom();
    
    private List<Registration> RegistrationDataOnDemand.data;
    
    @Autowired
    private OfferingDataOnDemand RegistrationDataOnDemand.offeringDataOnDemand;
    
    @Autowired
    private StudentDataOnDemand RegistrationDataOnDemand.studentDataOnDemand;
    
    public Registration RegistrationDataOnDemand.getNewTransientRegistration(int index) {
        Registration obj = new Registration();
        setAttended(obj, index);
        setOffering(obj, index);
        setPaymentMade(obj, index);
        setStudent(obj, index);
        return obj;
    }
    
    public void RegistrationDataOnDemand.setAttended(Registration obj, int index) {
        Boolean attended = true;
        obj.setAttended(attended);
    }
    
    public void RegistrationDataOnDemand.setOffering(Registration obj, int index) {
        Offering offering = offeringDataOnDemand.getRandomOffering();
        obj.setOffering(offering);
    }
    
    public void RegistrationDataOnDemand.setPaymentMade(Registration obj, int index) {
        Boolean paymentMade = true;
        obj.setPaymentMade(paymentMade);
    }
    
    public void RegistrationDataOnDemand.setStudent(Registration obj, int index) {
        Student student = studentDataOnDemand.getRandomStudent();
        obj.setStudent(student);
    }
    
    public Registration RegistrationDataOnDemand.getSpecificRegistration(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Registration obj = data.get(index);
        java.lang.Long id = obj.getId();
        return Registration.findRegistration(id);
    }
    
    public Registration RegistrationDataOnDemand.getRandomRegistration() {
        init();
        Registration obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return Registration.findRegistration(id);
    }
    
    public boolean RegistrationDataOnDemand.modifyRegistration(Registration obj) {
        return false;
    }
    
    public void RegistrationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Registration.findRegistrationEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Registration' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.rooina.coursemanager.model.Registration>();
        for (int i = 0; i < 10; i++) {
            Registration obj = getNewTransientRegistration(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
