// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.rooinaction.coursemanager.model.Offering;
import org.rooinaction.coursemanager.model.OfferingDataOnDemand;
import org.rooinaction.coursemanager.model.OfferingIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OfferingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OfferingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OfferingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OfferingIntegrationTest: @Transactional;
    
    @Autowired
    OfferingDataOnDemand OfferingIntegrationTest.dod;
    
    @Test
    public void OfferingIntegrationTest.testCountOfferings() {
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", dod.getRandomOffering());
        long count = Offering.countOfferings();
        Assert.assertTrue("Counter for 'Offering' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OfferingIntegrationTest.testFindOffering() {
        Offering obj = dod.getRandomOffering();
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Offering' failed to provide an identifier", id);
        obj = Offering.findOffering(id);
        Assert.assertNotNull("Find method for 'Offering' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Offering' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OfferingIntegrationTest.testFindAllOfferings() {
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", dod.getRandomOffering());
        long count = Offering.countOfferings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Offering', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Offering> result = Offering.findAllOfferings();
        Assert.assertNotNull("Find all method for 'Offering' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Offering' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OfferingIntegrationTest.testFindOfferingEntries() {
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", dod.getRandomOffering());
        long count = Offering.countOfferings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Offering> result = Offering.findOfferingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Offering' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Offering' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OfferingIntegrationTest.testFlush() {
        Offering obj = dod.getRandomOffering();
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Offering' failed to provide an identifier", id);
        obj = Offering.findOffering(id);
        Assert.assertNotNull("Find method for 'Offering' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOffering(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Offering' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfferingIntegrationTest.testMergeUpdate() {
        Offering obj = dod.getRandomOffering();
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Offering' failed to provide an identifier", id);
        obj = Offering.findOffering(id);
        boolean modified =  dod.modifyOffering(obj);
        Integer currentVersion = obj.getVersion();
        Offering merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Offering' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OfferingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", dod.getRandomOffering());
        Offering obj = dod.getNewTransientOffering(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Offering' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Offering' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Offering' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OfferingIntegrationTest.testRemove() {
        Offering obj = dod.getRandomOffering();
        Assert.assertNotNull("Data on demand for 'Offering' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Offering' failed to provide an identifier", id);
        obj = Offering.findOffering(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Offering' with identifier '" + id + "'", Offering.findOffering(id));
    }
    
}
