// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.web;

import java.io.Serializable;

privileged aspect RegisterStudentSearchForm_Roo_Serializable {
    
    declare parents: RegisterStudentSearchForm implements Serializable;
    
    private static final long RegisterStudentSearchForm.serialVersionUID = 1L;
    
}
