// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import java.util.Set;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyDetailsView;
import org.rooinaction.coursemanager.shared.CourseTypeEnum;
import org.rooinaction.coursemanager.web.gwt.proxies.CourseProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TagProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TrainingProgramProxy;

public abstract class CourseMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<CourseProxy> {

    @UiField
    Element id;

    @UiField
    Element name;

    @UiField
    Element description;

    @UiField
    Element cost;

    @UiField
    Element maximumCapacity;

    @UiField
    Element courseType;

    @UiField
    Element trainingProgram;

    @UiField
    Element tags;

    @UiField
    Element offerings;

    @UiField
    Element version;

    CourseProxy proxy;

    public void setValue(CourseProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        name.setInnerText(proxy.getName() == null ? "" : String.valueOf(proxy.getName()));
        description.setInnerText(proxy.getDescription() == null ? "" : String.valueOf(proxy.getDescription()));
        cost.setInnerText(proxy.getCost() == null ? "" : String.valueOf(proxy.getCost()));
        maximumCapacity.setInnerText(proxy.getMaximumCapacity() == null ? "" : String.valueOf(proxy.getMaximumCapacity()));
        courseType.setInnerText(proxy.getCourseType() == null ? "" : String.valueOf(proxy.getCourseType()));
        trainingProgram.setInnerText(proxy.getTrainingProgram() == null ? "" : org.rooinaction.coursemanager.client.managed.ui.TrainingProgramProxyRenderer.instance().render(proxy.getTrainingProgram()));
        tags.setInnerText(proxy.getTags() == null ? "" : org.rooinaction.coursemanager.client.scaffold.place.CollectionRenderer.of(org.rooinaction.coursemanager.client.managed.ui.TagProxyRenderer.instance()).render(proxy.getTags()));
        offerings.setInnerText(proxy.getOfferings() == null ? "" : org.rooinaction.coursemanager.client.scaffold.place.CollectionRenderer.of(org.rooinaction.coursemanager.client.managed.ui.OfferingProxyRenderer.instance()).render(proxy.getOfferings()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
    }
}
