// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooina.coursemanager.model;

import java.io.Serializable;

privileged aspect PaymentPK_Roo_Serializable {
    
    declare parents: PaymentPK implements Serializable;
    
    private static final long PaymentPK.serialVersionUID = 1L;
    
}
