// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.i18n.client.NumberFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import java.util.HashSet;
import java.util.Set;
import org.rooinaction.coursemanager.client.scaffold.place.AbstractProxyListView;
import org.rooinaction.coursemanager.shared.CourseTypeEnum;
import org.rooinaction.coursemanager.web.gwt.proxies.CourseProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TagProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.TrainingProgramProxy;

public abstract class CourseListView_Roo_Gwt extends AbstractProxyListView<CourseProxy> {

    @UiField
    CellTable<CourseProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("name");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getName());
            }
        }, "Name");
        paths.add("description");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.lang.String> renderer = new AbstractRenderer<java.lang.String>() {

                public String render(java.lang.String obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getDescription());
            }
        }, "Description");
        paths.add("cost");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.math.BigDecimal> renderer = new AbstractRenderer<java.math.BigDecimal>() {

                public String render(java.math.BigDecimal obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getCost());
            }
        }, "Cost");
        paths.add("maximumCapacity");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getMaximumCapacity());
            }
        }, "Maximum Capacity");
        paths.add("courseType");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<org.rooinaction.coursemanager.shared.CourseTypeEnum> renderer = new AbstractRenderer<org.rooinaction.coursemanager.shared.CourseTypeEnum>() {

                public String render(org.rooinaction.coursemanager.shared.CourseTypeEnum obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getCourseType());
            }
        }, "Course Type");
        paths.add("trainingProgram");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<org.rooinaction.coursemanager.web.gwt.proxies.TrainingProgramProxy> renderer = org.rooinaction.coursemanager.client.managed.ui.TrainingProgramProxyRenderer.instance();

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getTrainingProgram());
            }
        }, "Training Program");
        paths.add("tags");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.util.Set> renderer = org.rooinaction.coursemanager.client.scaffold.place.CollectionRenderer.of(org.rooinaction.coursemanager.client.managed.ui.TagProxyRenderer.instance());

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getTags());
            }
        }, "Tags");
        paths.add("offerings");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.util.Set> renderer = org.rooinaction.coursemanager.client.scaffold.place.CollectionRenderer.of(org.rooinaction.coursemanager.client.managed.ui.OfferingProxyRenderer.instance());

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getOfferings());
            }
        }, "Offerings");
        paths.add("version");
        table.addColumn(new TextColumn<CourseProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(CourseProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
    }
}
