// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package org.rooinaction.coursemanager.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.google.web.bindery.requestfactory.gwt.client.RequestFactoryEditorDriver;
import com.google.web.bindery.requestfactory.shared.RequestFactory;
import java.util.Collection;
import java.util.List;
import org.rooinaction.coursemanager.client.managed.activity.RegistrationEditActivityWrapper;
import org.rooinaction.coursemanager.client.managed.activity.RegistrationEditActivityWrapper.View;
import org.rooinaction.coursemanager.client.scaffold.place.ProxyEditView;
import org.rooinaction.coursemanager.client.scaffold.ui.*;
import org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.RegistrationProxy;
import org.rooinaction.coursemanager.web.gwt.proxies.StudentProxy;

public abstract class RegistrationMobileEditView_Roo_Gwt extends Composite implements View<RegistrationMobileEditView> {

    @UiField(provided = true)
    ValueListBox<StudentProxy> student = new ValueListBox<StudentProxy>(org.rooinaction.coursemanager.client.managed.ui.StudentProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<org.rooinaction.coursemanager.web.gwt.proxies.StudentProxy>());

    @UiField(provided = true)
    ValueListBox<OfferingProxy> offering = new ValueListBox<OfferingProxy>(org.rooinaction.coursemanager.client.managed.ui.OfferingProxyRenderer.instance(), new com.google.web.bindery.requestfactory.gwt.ui.client.EntityProxyKeyProvider<org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy>());

    public void setOfferingPickerValues(Collection<org.rooinaction.coursemanager.web.gwt.proxies.OfferingProxy> values) {
        offering.setAcceptableValues(values);
    }

    public void setStudentPickerValues(Collection<org.rooinaction.coursemanager.web.gwt.proxies.StudentProxy> values) {
        student.setAcceptableValues(values);
    }
}
