// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooinaction.coursemanager.model;

import org.rooinaction.coursemanager.model.StudentIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StudentIntegrationTest_Roo_Configurable {
    
    declare @type: StudentIntegrationTest: @Configurable;
    
}
