// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rooina.addons.standalone.jmxexample.model;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Blog_Roo_Configurable {
    
    declare @type: Blog: @Configurable;
    
}
